# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean compile package'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      inputs:
        containerRegistry: 'azuredockerconnection'
        repository: 'springbootmysql'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Visual Studio Enterprise(aa2d8073-cf46-4f53-abef-78339f602b9c)'
        appType: 'webAppContainer'
        WebAppName: 'travisspringbootmysql'
        DockerNamespace: 'travisdevopscontainers.azurecr.io'
        DockerRepository: '$(Build.Repository.Name)'
        DockerImageTag: '$(Build.BuildId)'